/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory;
import java.sql.SQLException; // ✅ Import added for SQLException

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JOHN MICHAEL ORTIGAS
 */
public class stockMonitoring extends javax.swing.JFrame {
    private DatabaseConnection db;

    /**
     * Creates new form stockMonitoring
     */
    public stockMonitoring() {
        initComponents();
        db = new DatabaseConnection("inventories"); // ✅ Fixed constructor with database name
        categories.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
            "product_id", "product_name", "price", "quantity", "created_at", "updated_at", "category"
        }));
        productTable.setAutoCreateRowSorter(true); // ✅ Enable table sorting
        db.Fetch(productTable);
    }

    public void refreshTable(){
        db.Fetch(productTable);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();
        categories = new javax.swing.JComboBox<>();
        find = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1040, 650));
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Stock Monitoring");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 10, 300, 40);

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Product  ID", "Product Name", "Price", "Quantity", "Created Date", "Updated Date", "Category"
            }
        ));
        jScrollPane1.setViewportView(productTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 140, 1040, 510);
        getContentPane().add(txtId);
        txtId.setBounds(380, 60, 260, 40);

        categories.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriesActionPerformed(evt);
            }
        });
        getContentPane().add(categories);
        categories.setBounds(250, 60, 110, 40);

        find.setText("Search");
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });
        getContentPane().add(find);
        find.setBounds(660, 60, 110, 40);

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(10, 10, 100, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void categoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriesActionPerformed

    }//GEN-LAST:event_categoriesActionPerformed

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
    String selectedColumn = (String) categories.getSelectedItem();
    String inputValue = txtId.getText().trim();

    if (inputValue.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a search value.");
        return;
    }

    db.searchProduct(productTable, selectedColumn, inputValue); // ✅ Clean, reusable call

    }//GEN-LAST:event_findActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    public javax.swing.JComboBox<String> getCategories() {
        return categories;
    }



public static void main(String args[]) {
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        java.util.logging.Logger.getLogger(stockMonitoring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    java.awt.EventQueue.invokeLater(() -> {
        new stockMonitoring().setVisible(true);
    });
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JComboBox<String> categories;
    private javax.swing.JButton find;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productTable;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
